var posts = {}
posts['ocd-division/country:ca/province:bc'] = []
posts['ocd-division/country:ca/province:bc'].push("Abbotsford-Mission")
posts['ocd-division/country:ca/province:bc'].push("Abbotsford South")
posts['ocd-division/country:ca/province:bc'].push("Abbotsford West")
posts['ocd-division/country:ca/province:bc'].push("Alberni-Pacific Rim")
posts['ocd-division/country:ca/province:bc'].push("Boundary-Similkameen")
posts['ocd-division/country:ca/province:bc'].push("Burnaby-Deer Lake")
posts['ocd-division/country:ca/province:bc'].push("Burnaby-Edmonds")
posts['ocd-division/country:ca/province:bc'].push("Burnaby-Lougheed")
posts['ocd-division/country:ca/province:bc'].push("Burnaby North")
posts['ocd-division/country:ca/province:bc'].push("Cariboo-Chilcotin")
posts['ocd-division/country:ca/province:bc'].push("Cariboo North")
posts['ocd-division/country:ca/province:bc'].push("Chilliwack")
posts['ocd-division/country:ca/province:bc'].push("Chilliwack-Hope")
posts['ocd-division/country:ca/province:bc'].push("Columbia River-Revelstoke")
posts['ocd-division/country:ca/province:bc'].push("Comox Valley")
posts['ocd-division/country:ca/province:bc'].push("Coquitlam-Burke Mountain")
posts['ocd-division/country:ca/province:bc'].push("Coquitlam-Maillardville")
posts['ocd-division/country:ca/province:bc'].push("Cowichan Valley")
posts['ocd-division/country:ca/province:bc'].push("Delta North")
posts['ocd-division/country:ca/province:bc'].push("Delta South")
posts['ocd-division/country:ca/province:bc'].push("Esquimalt-Royal Roads")
posts['ocd-division/country:ca/province:bc'].push("Fort Langley-Aldergrove")
posts['ocd-division/country:ca/province:bc'].push("Fraser-Nicola")
posts['ocd-division/country:ca/province:bc'].push("Juan de Fuca")
posts['ocd-division/country:ca/province:bc'].push("Kamloops-North Thompson")
posts['ocd-division/country:ca/province:bc'].push("Kamloops-South Thompson")
posts['ocd-division/country:ca/province:bc'].push("Kelowna-Lake Country")
posts['ocd-division/country:ca/province:bc'].push("Kelowna-Mission")
posts['ocd-division/country:ca/province:bc'].push("Kootenay East")
posts['ocd-division/country:ca/province:bc'].push("Kootenay West")
posts['ocd-division/country:ca/province:bc'].push("Langley")
posts['ocd-division/country:ca/province:bc'].push("Maple Ridge-Mission")
posts['ocd-division/country:ca/province:bc'].push("Maple Ridge-Pitt Meadows")
posts['ocd-division/country:ca/province:bc'].push("Nanaimo")
posts['ocd-division/country:ca/province:bc'].push("Nanaimo-North Cowichan")
posts['ocd-division/country:ca/province:bc'].push("Nechako Lakes")
posts['ocd-division/country:ca/province:bc'].push("Nelson-Creston")
posts['ocd-division/country:ca/province:bc'].push("New Westminster")
posts['ocd-division/country:ca/province:bc'].push("North Coast")
posts['ocd-division/country:ca/province:bc'].push("North Island")
posts['ocd-division/country:ca/province:bc'].push("North Vancouver-Lonsdale")
posts['ocd-division/country:ca/province:bc'].push("North Vancouver-Seymour")
posts['ocd-division/country:ca/province:bc'].push("Oak Bay-Gordon Head")
posts['ocd-division/country:ca/province:bc'].push("Parksville-Qualicum")
posts['ocd-division/country:ca/province:bc'].push("Peace River North")
posts['ocd-division/country:ca/province:bc'].push("Peace River South")
posts['ocd-division/country:ca/province:bc'].push("Penticton")
posts['ocd-division/country:ca/province:bc'].push("Port Coquitlam")
posts['ocd-division/country:ca/province:bc'].push("Port Moody-Coquitlam")
posts['ocd-division/country:ca/province:bc'].push("Powell River-Sunshine Coast")
posts['ocd-division/country:ca/province:bc'].push("Prince George-Mackenzie")
posts['ocd-division/country:ca/province:bc'].push("Prince George-Valemount")
posts['ocd-division/country:ca/province:bc'].push("Richmond Centre")
posts['ocd-division/country:ca/province:bc'].push("Richmond East")
posts['ocd-division/country:ca/province:bc'].push("Richmond-Steveston")
posts['ocd-division/country:ca/province:bc'].push("Saanich North and the Islands")
posts['ocd-division/country:ca/province:bc'].push("Saanich South")
posts['ocd-division/country:ca/province:bc'].push("Shuswap")
posts['ocd-division/country:ca/province:bc'].push("Skeena")
posts['ocd-division/country:ca/province:bc'].push("Stikine")
posts['ocd-division/country:ca/province:bc'].push("Surrey-Cloverdale")
posts['ocd-division/country:ca/province:bc'].push("Surrey-Fleetwood")
posts['ocd-division/country:ca/province:bc'].push("Surrey-Green Timbers")
posts['ocd-division/country:ca/province:bc'].push("Surrey-Newton")
posts['ocd-division/country:ca/province:bc'].push("Surrey-Panorama")
posts['ocd-division/country:ca/province:bc'].push("Surrey-Tynehead")
posts['ocd-division/country:ca/province:bc'].push("Surrey-Whalley")
posts['ocd-division/country:ca/province:bc'].push("Surrey-White Rock")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Fairview")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-False Creek")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Fraserview")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Hastings")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Kensington")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Kingsway")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Langara")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Mount Pleasant")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Point Grey")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-Quilchena")
posts['ocd-division/country:ca/province:bc'].push("Vancouver-West End")
posts['ocd-division/country:ca/province:bc'].push("Vernon-Monashee")
posts['ocd-division/country:ca/province:bc'].push("Victoria-Beacon Hill")
posts['ocd-division/country:ca/province:bc'].push("Victoria-Swan Lake")
posts['ocd-division/country:ca/province:bc'].push("West Vancouver-Capilano")
posts['ocd-division/country:ca/province:bc'].push("West Vancouver-Sea to Sky")
posts['ocd-division/country:ca/province:bc'].push("Westside-Kelowna")
posts['ocd-division/country:ca/province:sk'] = []
posts['ocd-division/country:ca/province:sk'].push("Arm River-Watrous")
posts['ocd-division/country:ca/province:sk'].push("Athabasca")
posts['ocd-division/country:ca/province:sk'].push("Batoche")
posts['ocd-division/country:ca/province:sk'].push("Biggar")
posts['ocd-division/country:ca/province:sk'].push("Cannington")
posts['ocd-division/country:ca/province:sk'].push("Canora-Pelly")
posts['ocd-division/country:ca/province:sk'].push("Carrot River Valley")
posts['ocd-division/country:ca/province:sk'].push("Cumberland")
posts['ocd-division/country:ca/province:sk'].push("Cut Knife-Turtleford")
posts['ocd-division/country:ca/province:sk'].push("Cypress Hills")
posts['ocd-division/country:ca/province:sk'].push("Estevan")
posts['ocd-division/country:ca/province:sk'].push("Humboldt")
posts['ocd-division/country:ca/province:sk'].push("Indian Head-Milestone")
posts['ocd-division/country:ca/province:sk'].push("Kelvington-Wadena")
posts['ocd-division/country:ca/province:sk'].push("Kindersley")
posts['ocd-division/country:ca/province:sk'].push("Last Mountain-Touchwood")
posts['ocd-division/country:ca/province:sk'].push("Lloydminster")
posts['ocd-division/country:ca/province:sk'].push("Martensville")
posts['ocd-division/country:ca/province:sk'].push("Meadow Lake")
posts['ocd-division/country:ca/province:sk'].push("Melfort")
posts['ocd-division/country:ca/province:sk'].push("Melville-Saltcoats")
posts['ocd-division/country:ca/province:sk'].push("Moose Jaw North")
posts['ocd-division/country:ca/province:sk'].push("Moose Jaw Wakamow")
posts['ocd-division/country:ca/province:sk'].push("Moosomin")
posts['ocd-division/country:ca/province:sk'].push("Prince Albert Carlton")
posts['ocd-division/country:ca/province:sk'].push("Prince Albert Northcote")
posts['ocd-division/country:ca/province:sk'].push("Regina Coronation Park")
posts['ocd-division/country:ca/province:sk'].push("Regina Dewdney")
posts['ocd-division/country:ca/province:sk'].push("Regina Douglas Park")
posts['ocd-division/country:ca/province:sk'].push("Regina Elphinstone-Centre")
posts['ocd-division/country:ca/province:sk'].push("Regina Lakeview")
posts['ocd-division/country:ca/province:sk'].push("Regina Northeast")
posts['ocd-division/country:ca/province:sk'].push("Regina Qu'Appelle Valley")
posts['ocd-division/country:ca/province:sk'].push("Regina Rosemont")
posts['ocd-division/country:ca/province:sk'].push("Regina South")
posts['ocd-division/country:ca/province:sk'].push("Regina Walsh Acres")
posts['ocd-division/country:ca/province:sk'].push("Regina Wascana Plains")
posts['ocd-division/country:ca/province:sk'].push("Rosetown-Elrose")
posts['ocd-division/country:ca/province:sk'].push("Rosthern-Shellbrook")
posts['ocd-division/country:ca/province:sk'].push("Saskatchewan Rivers")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Centre")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Eastview")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Fairview")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Greystone")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Massey Place")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Meewasin")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Northwest")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Nutana")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Riversdale")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Silver Springs")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Southeast")
posts['ocd-division/country:ca/province:sk'].push("Saskatoon Sutherland")
posts['ocd-division/country:ca/province:sk'].push("Swift Current")
posts['ocd-division/country:ca/province:sk'].push("The Battlefords")
posts['ocd-division/country:ca/province:sk'].push("Thunder Creek")
posts['ocd-division/country:ca/province:sk'].push("Weyburn-Big Muddy")
posts['ocd-division/country:ca/province:sk'].push("Wood River")
posts['ocd-division/country:ca/province:sk'].push("Yorkton")
