# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('report', jsonfield.fields.JSONField(null=True)),
                ('warnings', models.TextField()),
                ('exception', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
