# Generated by Django 1.9a1 on 2015-11-03 00:40

from django.db import migrations, models


class JSONField(models.TextField):
    """Mocks jsonfield 0.92's column-type behaviour."""

    def db_type(self, connection):
        if connection.vendor == 'postgresql' and connection.pg_version >= 90300:
            return 'json'
        return super().db_type(connection)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('report', JSONField(null=True)),
                ('warnings', models.TextField()),
                ('exception', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
