# Generated by Django 1.10.5 on 2017-02-24 02:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
