# Generated by Django 4.2.16 on 2024-11-11 20:49

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170224_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
